events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    upstream flask_app {
        server flask:5000;
    }
    
    server {
        listen 80;
        server_name wonderfull-planner.ru www.wonderfull-planner.ru
                   чудесный-планер.рф www.чудесный-планер.рф
                   xn----7sbbaalcwbe2ag2acee2a7c.xn--p1ai
                   www.xn----7sbbaalcwbe2ag2acee2a7c.xn--p1ai;
        
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        
        location /static/ {
            alias /usr/share/nginx/static/;
            expires 365d;
            access_log off;
        }
        
        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
