version = 5.3.1
archive_dir = /etc/letsencrypt/archive/wonderfull-planner.ru
cert = /etc/letsencrypt/live/wonderfull-planner.ru/cert.pem
privkey = /etc/letsencrypt/live/wonderfull-planner.ru/privkey.pem
chain = /etc/letsencrypt/live/wonderfull-planner.ru/chain.pem
fullchain = /etc/letsencrypt/live/wonderfull-planner.ru/fullchain.pem
[renewalparams]
account = 807faa92a87cc53bbe6dd6667c0abe21
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-02-12T15:14:27
